# https://docs.travis-ci.com/user/
language: python

python:
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8

# required for python >= 3.7
dist: xenial

env:
- PIPENV_IGNORE_VIRTUALENVS=1

install:
# pipenv v2020.4.1a2 / v2020.5.28 removed support for python3.4 (in vendored pkg_resources)
# https://github.com/pypa/pipenv/commit/3f9f359c0e563d30a60f0d1e4633eea9f964b610#diff-eec907d96e76285f711fb3cb5ab5469dR92
- pip install --upgrade 'pipenv>=2018.10.9,<v2020.5.28'
- if [ "$TRAVIS_PYTHON_VERSION" = "3.4" ]; then mv Pipfile.lock-python3.4 Pipfile.lock; fi
- pipenv install --python "$TRAVIS_PYTHON_VERSION" --deploy --dev
- pipenv graph

script:
- pipenv run pylint pylint_import_requirements
- pipenv run pytest --cov=pylint_import_requirements --cov-report=term-missing --cov-fail-under=83
